POST http://localhost:5500/api/item 
Content-Type: application/json

{
"item": "New"
}

###

GET http://localhost:5500/api/items 
Content-Type: application/json


###

PUT http://localhost:5500/api/item/654aefad5fb91fae8c55f192
Content-Type: application/json

{
"item": "This is the second todo item updated!!"
}


###
DELETE http://localhost:5500/api/item/654af0bec3651052f087d1a3 
Content-Type: application/json
